services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python /code/mainashop/manage.py migrate
  web_run:
    extends:
      service: web
    command: python /code/mainashop/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - web_migrate
    cache:
      image: redis:7.2.4
      restart: always
      volumes:
        - redis_data:/data
volumes:
  redis_data:
